In [2]:
import numpy as np 
import pandas as pd 
import plotly as plty
import matplotlib.pyplot as plt

test=pd.read_parquet('/Users/dlakhdar/Downloads/test_meta.parquet')
train=pd.read_parquet('/Users/dlakhdar/Downloads/train_meta.parquet')

In [3]:
train

,batch_id,event_id,first_pulse_index,last_pulse_index,azimuth,zenith
0,1,24,0,60,5.029555,2.087498
1,1,41,61,111,0.417742,1.549686
2,1,59,112,147,1.160466,2.401942
3,1,67,148,289,5.845952,0.759054
4,1,72,290,351,0.653719,0.939117
...,...,...,...,...,...,...
131953919,660,2147483597,24339210,24339349,5.895612,0.333071
131953920,660,2147483603,24339350,24339383,3.273695,1.503301
131953921,660,2147483617,24339384,24339424,2.945376,1.723253
131953922,660,2147483626,24339425,24339499,1.616582,1.937025
131953923,660,2147483627,24339500,24339550,3.062654,1.842630

In [21]:
batch=pd.read_parquet('/Users/dlakhdar/Downloads/batch_1.parquet')
sensors=pd.read_csv('/Users/dlakhdar/Downloads/sensor_geometry.csv')

In [45]:
norm= np.sqrt((sensors.x)**2+(sensors.y)**2+(sensors.z)**2)

for i in ['x_','y_','z_']:
    sensors[i]=sensors.x/norm

def convert_cartesian_to_spherical(x,y,z):
    """
    Takes three pandas columns x,y,z each a cartesian component and spits out two columns θ,ϕ 
    """
    
    θ=np.arccos(z)
    ϕ=np.arcsin(x)/np.cos(θ)
    
    return (θ,ϕ)

zenith, azimuth=convert_cartesian_to_spherical(sensors.x_,sensors.y_,sensors.z_)
sensors['zenith']=zenith
sensors['azimuth']=azimuth

In [46]:
sensors

,sensor_id,x,y,z,x^,y^,z^,x_,y_,z_,zenith,azimuth
0,0,-256.14,-521.08,496.03,-0.335411,-0.682345,0.649542,-0.335411,-0.682345,0.649542,0.863814,-0.526588
1,1,-256.14,-521.08,479.01,-0.340287,-0.692266,0.636375,-0.340287,-0.692266,0.636375,0.881007,-0.545626
2,2,-256.14,-521.08,461.99,-0.345201,-0.702262,0.622626,-0.345201,-0.702262,0.622626,0.898702,-0.566075
3,3,-256.14,-521.08,444.97,-0.350145,-0.712319,0.608276,-0.350145,-0.712319,0.608276,0.916909,-0.588097
4,4,-256.14,-521.08,427.95,-0.355109,-0.722418,0.593304,-0.355109,-0.722418,0.593304,0.935639,-0.611880
...,...,...,...,...,...,...,...,...,...,...,...,...
5155,5155,-10.97,6.72,-472.39,-0.023214,0.014220,-0.999629,-0.023214,0.014220,-0.999629,3.114366,0.023224
5156,5156,-10.97,6.72,-479.39,-0.022875,0.014013,-0.999640,-0.022875,0.014013,-0.999640,3.114764,0.022885
5157,5157,-10.97,6.72,-486.40,-0.022546,0.013811,-0.999650,-0.022546,0.013811,-0.999650,3.115150,0.022555
5158,5158,-10.97,6.72,-493.41,-0.022225,0.013615,-0.999660,-0.022225,0.013615,-0.999660,3.115526,0.022235
5159,5159,-10.97,6.72,-500.73,-0.021901,0.013416,-0.999670,-0.021901,0.013416,-0.999670,3.115907,0.021910